name: Compile, test and check the docs

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ci
  cancel-in-progress: true

jobs:

  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v3
    secrets: inherit

  build:
    uses: nikita-volkov/check-haskell-fast.github-actions-workflow/.github/workflows/check-haskell-fast.yaml@v1
    secrets: inherit
  